create table if not exists public.active_lives_snapshots (
  id bigint generated by default as identity primary key,
  collection_slot bigint not null unique,
  total_active_lives integer not null check (total_active_lives >= 0),
  total_active_holders integer not null check (total_active_holders >= 0),
  total_active_dependents integer not null check (total_active_dependents >= 0),
  consulted_at timestamptz not null,
  collected_at timestamptz not null default now()
);

create index if not exists active_lives_snapshots_consulted_at_idx
  on public.active_lives_snapshots (consulted_at desc);

alter table public.active_lives_snapshots enable row level security;

revoke insert, update, delete on public.active_lives_snapshots from anon, authenticated;
grant select on public.active_lives_snapshots to anon, authenticated;

drop policy if exists "Vidometro public read" on public.active_lives_snapshots;
create policy "Vidometro public read"
  on public.active_lives_snapshots
  for select
  to anon, authenticated
  using (true);

create or replace function public.vidometro_dashboard(
  p_from date default (current_date - 29),
  p_to date default current_date
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with params as (
    select
      (p_from::timestamp at time zone 'America/Fortaleza') as from_ts,
      ((p_to + 1)::timestamp at time zone 'America/Fortaleza') as to_ts,
      case when (p_to - p_from) <= 3 then 'hour' else 'day' end as sampling
  ),
  period_rows as (
    select s.*
    from public.active_lives_snapshots s
    cross join params p
    where s.consulted_at >= p.from_ts
      and s.consulted_at < p.to_ts
  ),
  first_row as (
    select * from period_rows order by consulted_at asc, id asc limit 1
  ),
  last_row as (
    select * from period_rows order by consulted_at desc, id desc limit 1
  ),
  latest_row as (
    select *
    from public.active_lives_snapshots
    order by collected_at desc, id desc
    limit 1
  ),
  trend_candidates as (
    select
      s.*,
      date_trunc(p.sampling, s.consulted_at at time zone 'America/Fortaleza') as bucket
    from period_rows s
    cross join params p
  ),
  trend_rows as (
    select distinct on (bucket) *
    from trend_candidates
    order by bucket, consulted_at desc, id desc
  ),
  recent_rows as (
    select *
    from public.active_lives_snapshots
    order by collected_at desc, id desc
    limit 5
  )
  select jsonb_build_object(
    'sampling', (select sampling from params),
    'latest', (
      select jsonb_build_object(
        'totalVidasAtivas', total_active_lives,
        'totalTitularesAtivos', total_active_holders,
        'totalDependentesAtivos', total_active_dependents,
        'dataConsulta', consulted_at,
        'collectedAt', collected_at
      ) from latest_row
    ),
    'first', (
      select jsonb_build_object(
        'totalVidasAtivas', total_active_lives,
        'totalTitularesAtivos', total_active_holders,
        'totalDependentesAtivos', total_active_dependents,
        'dataConsulta', consulted_at,
        'collectedAt', collected_at
      ) from first_row
    ),
    'last', (
      select jsonb_build_object(
        'totalVidasAtivas', total_active_lives,
        'totalTitularesAtivos', total_active_holders,
        'totalDependentesAtivos', total_active_dependents,
        'dataConsulta', consulted_at,
        'collectedAt', collected_at
      ) from last_row
    ),
    'growth', (
      select jsonb_build_object(
        'totalVidasAtivas', jsonb_build_object(
          'absolute', l.total_active_lives - f.total_active_lives,
          'percentage', case
            when f.total_active_lives = 0 then null
            else round(((l.total_active_lives - f.total_active_lives) * 100.0 / f.total_active_lives)::numeric, 2)
          end
        ),
        'totalTitularesAtivos', jsonb_build_object(
          'absolute', l.total_active_holders - f.total_active_holders,
          'percentage', case
            when f.total_active_holders = 0 then null
            else round(((l.total_active_holders - f.total_active_holders) * 100.0 / f.total_active_holders)::numeric, 2)
          end
        ),
        'totalDependentesAtivos', jsonb_build_object(
          'absolute', l.total_active_dependents - f.total_active_dependents,
          'percentage', case
            when f.total_active_dependents = 0 then null
            else round(((l.total_active_dependents - f.total_active_dependents) * 100.0 / f.total_active_dependents)::numeric, 2)
          end
        )
      )
      from first_row f
      cross join last_row l
    ),
    'trend', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'totalVidasAtivas', total_active_lives,
          'totalTitularesAtivos', total_active_holders,
          'totalDependentesAtivos', total_active_dependents,
          'dataConsulta', consulted_at,
          'collectedAt', collected_at
        ) order by bucket
      )
      from trend_rows
    ), '[]'::jsonb),
    'recent', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'totalVidasAtivas', total_active_lives,
          'totalTitularesAtivos', total_active_holders,
          'totalDependentesAtivos', total_active_dependents,
          'dataConsulta', consulted_at,
          'collectedAt', collected_at
        ) order by collected_at desc
      )
      from recent_rows
    ), '[]'::jsonb)
  );
$$;

revoke all on function public.vidometro_dashboard(date, date) from public;
grant execute on function public.vidometro_dashboard(date, date) to anon, authenticated;

-- A coleta é executada no Supabase, sem depender de um servidor de aplicação.
-- Os segredos `project_url` e `publishable_key` devem ser cadastrados uma única
-- vez no Supabase Vault. O README contém os comandos de bootstrap.
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;
create extension if not exists supabase_vault with schema vault;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.invoke_vidometro_collector()
returns bigint
language plpgsql
security definer
set search_path = public, extensions, vault, pg_catalog
as $$
declare
  project_url text;
  publishable_key text;
  request_id bigint;
begin
  select decrypted_secret
    into project_url
    from vault.decrypted_secrets
   where name = 'project_url'
   limit 1;

  select decrypted_secret
    into publishable_key
    from vault.decrypted_secrets
   where name = 'publishable_key'
   limit 1;

  if project_url is null or publishable_key is null then
    raise warning 'Vidometro: configure project_url e publishable_key no Vault para ativar a coleta.';
    return null;
  end if;

  select net.http_post(
    url := rtrim(project_url, '/') || '/functions/v1/collect-active-lives',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', publishable_key,
      'Authorization', 'Bearer ' || publishable_key
    ),
    body := jsonb_build_object('source', 'supabase-cron'),
    timeout_milliseconds := 15000
  ) into request_id;

  return request_id;
end;
$$;

do $$
declare
  existing_job bigint;
begin
  select jobid
    into existing_job
    from cron.job
   where jobname = 'vidometro-collect-active-lives'
   limit 1;

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;

  perform cron.schedule(
    'vidometro-collect-active-lives',
    '*/5 * * * *',
    'select private.invoke_vidometro_collector();'
  );
end;
$$;
