create table if not exists public.active_lives_snapshots (
  id bigint generated by default as identity primary key,
  collection_date date not null unique,
  total_active_lives integer not null check (total_active_lives >= 0),
  total_active_holders integer not null check (total_active_holders >= 0),
  total_active_dependents integer not null check (total_active_dependents >= 0),
  consulted_at timestamptz not null,
  collected_at timestamptz not null default now()
);

create index if not exists active_lives_snapshots_collection_date_idx
  on public.active_lives_snapshots (collection_date desc);

alter table public.active_lives_snapshots enable row level security;

revoke insert, update, delete on public.active_lives_snapshots from anon, authenticated;
grant select on public.active_lives_snapshots to anon, authenticated;

drop policy if exists "Vidometro public read" on public.active_lives_snapshots;
create policy "Vidometro public read"
  on public.active_lives_snapshots
  for select
  to anon, authenticated
  using (true);

create or replace function public.vidometro_dashboard(
  p_from date default (current_date - 29),
  p_to date default current_date
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with period_rows as (
    select s.*
    from public.active_lives_snapshots s
    where s.collection_date between p_from and p_to
  ),
  first_row as (
    select * from period_rows order by collection_date asc limit 1
  ),
  last_row as (
    select * from period_rows order by collection_date desc limit 1
  ),
  latest_row as (
    select *
    from public.active_lives_snapshots
    order by collected_at desc, id desc
    limit 1
  ),
  recent_rows as (
    select *
    from public.active_lives_snapshots
    order by collection_date desc
    limit 5
  )
  select jsonb_build_object(
    'sampling', 'day',
    'latest', (
      select jsonb_build_object(
        'totalVidasAtivas', total_active_lives,
        'totalTitularesAtivos', total_active_holders,
        'totalDependentesAtivos', total_active_dependents,
        'dataConsulta', consulted_at,
        'collectedAt', collected_at
      ) from latest_row
    ),
    'first', (
      select jsonb_build_object(
        'totalVidasAtivas', total_active_lives,
        'totalTitularesAtivos', total_active_holders,
        'totalDependentesAtivos', total_active_dependents,
        'dataConsulta', consulted_at,
        'collectedAt', collected_at
      ) from first_row
    ),
    'last', (
      select jsonb_build_object(
        'totalVidasAtivas', total_active_lives,
        'totalTitularesAtivos', total_active_holders,
        'totalDependentesAtivos', total_active_dependents,
        'dataConsulta', consulted_at,
        'collectedAt', collected_at
      ) from last_row
    ),
    'growth', (
      select jsonb_build_object(
        'totalVidasAtivas', jsonb_build_object(
          'absolute', l.total_active_lives - f.total_active_lives,
          'percentage', case
            when f.total_active_lives = 0 then null
            else round(((l.total_active_lives - f.total_active_lives) * 100.0 / f.total_active_lives)::numeric, 2)
          end
        ),
        'totalTitularesAtivos', jsonb_build_object(
          'absolute', l.total_active_holders - f.total_active_holders,
          'percentage', case
            when f.total_active_holders = 0 then null
            else round(((l.total_active_holders - f.total_active_holders) * 100.0 / f.total_active_holders)::numeric, 2)
          end
        ),
        'totalDependentesAtivos', jsonb_build_object(
          'absolute', l.total_active_dependents - f.total_active_dependents,
          'percentage', case
            when f.total_active_dependents = 0 then null
            else round(((l.total_active_dependents - f.total_active_dependents) * 100.0 / f.total_active_dependents)::numeric, 2)
          end
        )
      )
      from first_row f
      cross join last_row l
    ),
    'trend', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'totalVidasAtivas', total_active_lives,
          'totalTitularesAtivos', total_active_holders,
          'totalDependentesAtivos', total_active_dependents,
          'dataConsulta', consulted_at,
          'collectedAt', collected_at
        ) order by collection_date
      )
      from period_rows
    ), '[]'::jsonb),
    'recent', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'totalVidasAtivas', total_active_lives,
          'totalTitularesAtivos', total_active_holders,
          'totalDependentesAtivos', total_active_dependents,
          'dataConsulta', consulted_at,
          'collectedAt', collected_at
        ) order by collection_date desc
      )
      from recent_rows
    ), '[]'::jsonb)
  );
$$;

revoke all on function public.vidometro_dashboard(date, date) from public;
grant execute on function public.vidometro_dashboard(date, date) to anon, authenticated;

-- O cron roda a cada cinco minutos, mas a tabela mantém somente uma linha por dia.
-- Cada nova coleta atualiza a linha do respectivo dia, preservando a última leitura diária.
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;
create extension if not exists supabase_vault with schema vault;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.invoke_vidometro_collector()
returns bigint
language plpgsql
security definer
set search_path = public, extensions, vault, pg_catalog
as $$
declare
  project_url text;
  secret_key text;
  request_id bigint;
begin
  select decrypted_secret
    into project_url
    from vault.decrypted_secrets
   where name = 'project_url'
   limit 1;

  select decrypted_secret
    into secret_key
    from vault.decrypted_secrets
   where name = 'collector_secret_key'
   limit 1;

  if project_url is null or secret_key is null then
    raise warning 'Vidometro: configure project_url e collector_secret_key no Vault para ativar a coleta.';
    return null;
  end if;

  select net.http_post(
    url := rtrim(project_url, '/') || '/functions/v1/collect-active-lives',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', secret_key
    ),
    body := jsonb_build_object('source', 'supabase-cron'),
    timeout_milliseconds := 15000
  ) into request_id;

  return request_id;
end;
$$;

do $$
declare
  existing_job bigint;
begin
  select jobid
    into existing_job
    from cron.job
   where jobname = 'vidometro-collect-active-lives'
   limit 1;

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;

  perform cron.schedule(
    'vidometro-collect-active-lives',
    '*/5 * * * *',
    'select private.invoke_vidometro_collector();'
  );
end;
$$;
