-- O histórico consolidado continua em active_lives_snapshots com uma única linha por dia.
-- Esta tabela mantém apenas uma janela operacional curta para o filtro Realtime.
create table if not exists public.active_lives_realtime_samples (
  id bigint generated by default as identity primary key,
  collection_date date not null,
  total_active_lives integer not null check (total_active_lives >= 0),
  total_active_holders integer not null check (total_active_holders >= 0),
  total_active_dependents integer not null check (total_active_dependents >= 0),
  consulted_at timestamptz not null unique,
  collected_at timestamptz not null default now()
);

create index if not exists active_lives_realtime_samples_date_idx
  on public.active_lives_realtime_samples (collection_date, collected_at);

alter table public.active_lives_realtime_samples enable row level security;

revoke insert, update, delete on public.active_lives_realtime_samples from anon, authenticated;
grant select on public.active_lives_realtime_samples to anon, authenticated;

drop policy if exists "Vidometro realtime public read" on public.active_lives_realtime_samples;
create policy "Vidometro realtime public read"
  on public.active_lives_realtime_samples
  for select
  to anon, authenticated
  using (true);

create or replace function public.vidometro_realtime()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with today_value as (
    select (now() at time zone 'America/Fortaleza')::date as day
  ),
  period_rows as (
    select s.*
    from public.active_lives_realtime_samples s
    cross join today_value t
    where s.collection_date = t.day
  ),
  first_row as (
    select * from period_rows order by collected_at asc, id asc limit 1
  ),
  last_row as (
    select * from period_rows order by collected_at desc, id desc limit 1
  ),
  previous_row as (
    select * from period_rows order by collected_at desc, id desc offset 1 limit 1
  ),
  recent_days as (
    select *
    from public.active_lives_snapshots
    order by collection_date desc
    limit 5
  )
  select jsonb_build_object(
    'sampling', 'realtime',
    'latest', (
      select jsonb_build_object(
        'totalVidasAtivas', total_active_lives,
        'totalTitularesAtivos', total_active_holders,
        'totalDependentesAtivos', total_active_dependents,
        'dataConsulta', consulted_at,
        'collectedAt', collected_at
      ) from last_row
    ),
    'first', (
      select jsonb_build_object(
        'totalVidasAtivas', total_active_lives,
        'totalTitularesAtivos', total_active_holders,
        'totalDependentesAtivos', total_active_dependents,
        'dataConsulta', consulted_at,
        'collectedAt', collected_at
      ) from first_row
    ),
    'last', (
      select jsonb_build_object(
        'totalVidasAtivas', total_active_lives,
        'totalTitularesAtivos', total_active_holders,
        'totalDependentesAtivos', total_active_dependents,
        'dataConsulta', consulted_at,
        'collectedAt', collected_at
      ) from last_row
    ),
    'growth', (
      select jsonb_build_object(
        'totalVidasAtivas', jsonb_build_object(
          'absolute', l.total_active_lives - p.total_active_lives,
          'percentage', case
            when p.total_active_lives = 0 then null
            else round(((l.total_active_lives - p.total_active_lives) * 100.0 / p.total_active_lives)::numeric, 3)
          end
        ),
        'totalTitularesAtivos', jsonb_build_object(
          'absolute', l.total_active_holders - p.total_active_holders,
          'percentage', case
            when p.total_active_holders = 0 then null
            else round(((l.total_active_holders - p.total_active_holders) * 100.0 / p.total_active_holders)::numeric, 3)
          end
        ),
        'totalDependentesAtivos', jsonb_build_object(
          'absolute', l.total_active_dependents - p.total_active_dependents,
          'percentage', case
            when p.total_active_dependents = 0 then null
            else round(((l.total_active_dependents - p.total_active_dependents) * 100.0 / p.total_active_dependents)::numeric, 3)
          end
        )
      )
      from previous_row p
      cross join last_row l
    ),
    'trend', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'totalVidasAtivas', total_active_lives,
          'totalTitularesAtivos', total_active_holders,
          'totalDependentesAtivos', total_active_dependents,
          'dataConsulta', consulted_at,
          'collectedAt', collected_at
        ) order by collected_at, id
      )
      from period_rows
    ), '[]'::jsonb),
    'recent', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'totalVidasAtivas', total_active_lives,
          'totalTitularesAtivos', total_active_holders,
          'totalDependentesAtivos', total_active_dependents,
          'dataConsulta', consulted_at,
          'collectedAt', collected_at
        ) order by collection_date desc
      )
      from recent_days
    ), '[]'::jsonb)
  );
$$;

revoke all on function public.vidometro_realtime() from public;
grant execute on function public.vidometro_realtime() to anon, authenticated;

-- Publica o fechamento diário e cada ciclo operacional para atualização imediata da UI.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'active_lives_snapshots'
  ) then
    alter publication supabase_realtime
      add table public.active_lives_snapshots;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'active_lives_realtime_samples'
  ) then
    alter publication supabase_realtime
      add table public.active_lives_realtime_samples;
  end if;
end
$$;
